version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: express
        versions: "> 6.0.0"
      - dependency-name: react
        versions: "> 16.0.0"
    # groups:
    #   npm-group:
    #     patterns:
    #       - "*"
