version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: express
        versions: "> 4.19.2"
      - dependency-name: react
        versions: "> 15.5.2"
    groups:
      npm-group:
        patterns:
          - "*"
