version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: express
        versions: "> 5.1.0"
      - dependency-name: react
        versions: "> 15.6.2"
    groups:
      npm-group:
        patterns:
          - "*"
